Setup/UI structure -- Build and style plugins page
M-AminAlizadeh/Logseq-marketplace pull request #2
Opened 2023-09-13 14:45 UTC by M-AminAlizadeh

The things that I did in this PR:

- Add one line to the end of each file
- Install and use react-router for routing
- Add favicon
- Build and style plugins page completely
- Add a search feature on the plugins page
- Fetch plugins and display them

2023-09-15 14:40 UTC, ahangarha requested changes
## ❌ Changes Required

This PR is much better than what I expected. 👍🏾 You have done great work so far. There is a tiny but important bug. Please check the comments.

I also made some other comments for optional changes. It is up to you to do it now or later. Maybe you can combine them while addressing the bug fix.

2023-09-15 14:40 UTC, ahangarha commented on public/index.html
> +    <link rel="icon" href="https://logseq.com/logo-with-border.5bf84f43.png" />
It is fine for now but let's keep in mind that the hash part of the name might get changed in the future.

2023-09-15 14:40 UTC, ahangarha commented on src/components/Plugin.jsx
> +  };
## ❌ Changes Required

What if the icon has such value: `./img/icon.png`?

I think you meant to remove `./` if the icon path starts with it.

2023-09-15 14:40 UTC, ahangarha commented on src/components/Plugin.jsx
> +        src={icon ? `https://raw.githubusercontent.com/logseq/marketplace/master/packages/${id}/${properIconUrl(icon)}` : 'https://img.icons8.com/pastel-glyph/64/page-not-found--v2.png'}
## 💡 Optional

Maybe it is better to extract this logic into a function like `getIconPath(icon)`.
It helps to keep the JSX part much cleaner.

I personally prefer to use a ternary operation when it is tiny and short.

2023-12-29 15:36 UTC, M-AminAlizadeh commented on src/components/Plugin.jsx
> +        src={icon ? `https://raw.githubusercontent.com/logseq/marketplace/master/packages/${id}/${properIconUrl(icon)}` : 'https://img.icons8.com/pastel-glyph/64/page-not-found--v2.png'}
Good Idea 
I changed it

2023-12-29 15:36 UTC, M-AminAlizadeh commented on public/index.html
> +    <link rel="icon" href="https://logseq.com/logo-with-border.5bf84f43.png" />
I changed it from absolute path to relative path.

2023-12-29 15:59 UTC, M-AminAlizadeh commented on src/components/Plugin.jsx
> +  };
Nice catch 
But according to the values of the icon key in each object, all of them have similar paths like `icon.png` or `./icon.png` or similar and I didn't see any value like `./dir/icon.png` or something like that.
I built this logic in `properIconUrl` according to the plugin objects that are already shared maybe in the future if something changes I will change the logic.
For now, I just changed the logic from `/` to `./`

2023-12-30 08:06 UTC, ahangarha approved these changes
Good work 👍🏾

2023-12-30 10:16 UTC, merged