Build Themes page
M-AminAlizadeh/Logseq-marketplace pull request #3
Opened 2024-01-03 11:02 UTC by M-AminAlizadeh

The things that I did in this PR:

- Fetch data about a list of themes and render it to the user with details
    - Icon image
    - Title name
    - Author name
    - Description
    - Repo link
- Add a searching feature between themes using the search box

2024-01-03 16:58 UTC, ahangarha commented on src/components/Theme.jsx
> +        <span title="Auhtor Username">{author}</span>
Typo

2024-01-03 17:13 UTC, ahangarha requested changes
## ❌ Changes required

Great work so far. In terms of functionality, the app is working as expected by there are multiple errors in the browser console. Apparently, I missed some of them in the previous PR review.

I shared some screenshots in the comments. Please address all the similar cases which are related to this PR. Others should be fixed in a separate PR.

2024-01-03 17:13 UTC, ahangarha commented on src/components/Themes.jsx
> +  themes: PropTypes.arrayOf.isRequired,
`PropTypes.arrayOf` of what?

![image](https://github.com/M-AminAlizadeh/Logseq-marketplace/assets/11241315/b4e5f0d6-f6b8-4933-b693-a988562155ae)

2024-01-03 17:13 UTC, ahangarha commented on src/components/Theme.jsx
> +  icon: PropTypes.string.isRequired,
What if we don't get `icon` from our source?

![image](https://github.com/M-AminAlizadeh/Logseq-marketplace/assets/11241315/de39ebf9-af13-4723-a8f2-5069f588d4b2)

2024-01-05 19:31 UTC, ahangarha requested changes
Good fixes.

I am not sure why changing from `npm` to `yarn` is done in this PR. revert the commit since it is not relevant.

Also I made some comments for PropTypes. Please address it.

Rest is good to me. Let's do final round of touches and merge.

2024-01-05 19:31 UTC, ahangarha commented on src/components/Theme.jsx
> +        <span title="Auhtor Username">{author}</span>
@M-AminAlizadeh 
Also check `Auhtor Username`

2024-01-05 19:31 UTC, ahangarha commented on package.json
> +    "yarn": "^1.22.21"
Not sure why you changed from `npm` to `yarn` but `yarn` is not a dependency for sure

2024-01-05 19:31 UTC, ahangarha commented on src/components/Themes.jsx
> +  themes: PropTypes.arrayOf(PropTypes.shape).isRequired,
`PropYypes.shape` should be used to define the shape of the complex data, typically an object.

Simple solutions: `PropTypes.array`.
Better solution: `PropTypes.arrayOf(PropTypes.object)`

We can make it even better but let's keep it this much for now.

2024-01-05 19:57 UTC, M-AminAlizadeh commented on package.json
> +    "yarn": "^1.22.21"
I changed it because of some issues about the conflict in eslint version system 
But no worries, I will do it later 
I reverted it to the `npm`.

2024-01-05 20:12 UTC, M-AminAlizadeh commented on src/components/Themes.jsx
> +  themes: PropTypes.arrayOf(PropTypes.shape).isRequired,
@ahangarha Your comment is right in an ordinary project without eslint 
But because in this project we are using `eslint` for preventing linter issues I have to follow [this](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md)
According to the document:

> By default this rule prevents vague prop types with more specific alternatives available (any, array, object), but any prop type can be disabled if desired. The defaults are chosen because they have obvious replacements. any should be replaced with, well, anything. array and object can be replaced with arrayOf and shape, respectively.

I used a better solution that you provided in the above comment but with new syntax that doesn't have any conflict with `eslint`

`arrayOf` instead of `array`
`shape` instead of `object`

2024-01-12 22:01 UTC, ahangarha approved these changes
Looks good 👍🏾 

It would be better to have a separate PR for the changes in the plugins page/components, but we can move forward.

Good work

2024-01-12 22:04 UTC, merged