Setup/add popup window
M-AminAlizadeh/Logseq-marketplace pull request #4
Opened 2024-04-23 12:52 UTC by M-AminAlizadeh

In this PR I tried to add a `Popup` window to the plugins (When a user clicks on more buttons of each plugin they can see the popup)

2024-04-24 05:50 UTC, ahangarha requested changes
The PR looks good overall. However, there are a couple of issues to address.

## 🚫 Changes required
Issues:
- Check my comment related to the wrong prop type.
- If the user narrows down the plugin list by search, clicking the "more" button crashes the app!

There might be some challenges for further development of the app but let's discuss/resolve them when needed.

## 💡 Optional changes
- Instead of a "more" button, the image and the title of the plugin can be clickable. This can improve UX.
- The whole idea of having a popup window is to get more information. As for the built-in marketplace in the Logseq app, the popup window can show the (parsed) content of the `READEME.md` file of the project.
Currently, you entirely remove the content of the page and replace it with the popup window. This is not usually the expected behavior for a popup window. It might be better to show the popup window as a popup window, meaning it should appear on top of the existing content.

Keep up your good work 🚀

2024-04-24 05:50 UTC, ahangarha commented on src/components/Plugins.jsx
> +  setPluginClickedID: PropTypes.string.isRequired,
The type `string` doesn't seem correct. It should be `func`. Right?

2024-05-02 14:12 UTC, ahangarha commented on src/components/Popup.jsx
> +      fetch('https://cdn.jsdelivr.net/gh/logseq/marketplace@master/plugins.json')
Haven't we fetched these data in the past? Isn't it better to use the existing data rather than fetching it again?

2024-05-02 14:16 UTC, ahangarha commented on src/components/Popup.jsx
> +        console.error('README not found in any branch');
In such cases, it might be better to show a message in place of readme content so that the user is informed about the (let's say unknown) issue. It is not a good idea to keep the user waiting for a result that will not be shown in the future.

2024-05-02 14:20 UTC, ahangarha requested changes
Good progress, but we still have some issues.

Apart from the points I have made in the new comments, we try to fetch readme from wrong addresses like `https://raw.githubusercontent.com//master/README.md`. This can be related to other logic of the `useEffect` hook that makes the call even if there is no value for the `repoURL`.

2024-05-03 12:13 UTC, M-AminAlizadeh commented on src/components/Popup.jsx
> +      fetch('https://cdn.jsdelivr.net/gh/logseq/marketplace@master/plugins.json')
Yes I forgot DRY

2024-05-03 15:37 UTC, ahangarha requested changes
Please check out these:
- You are still making multiple wrong requests to get the README file.
- There is an issue with prop types.
- Markdown documents are not parsed properly. I recommend using `markdown-it`.

![image](https://github.com/M-AminAlizadeh/Logseq-marketplace/assets/11241315/b8ad9e95-e853-4e80-83fb-3bf70f31bc7a)

Please check the browser console and network tab to verify the app behavior.

2024-05-13 11:58 UTC, ahangarha approved these changes
Good progress

I approve this PR thought there are some more tasks to do to finish the popup window feature.
- Improve the design. The popup should not become bigger than the view-port.
- Currently you are fetching both `main` and `master` branch. You should fetch one and only fetch the other if you get 404 response.
- The popup content (readme file) needs some styling. You may use `tailwind-typography` and use `prose` class to the wrapper to apply basic design.
- Some modifications needs to be applied on the readme file to correct the image path.

I think you can merge this PR and apply the mentioned items in follow up PRs, one PR for each.

2024-05-14 13:11 UTC, merged